# Generated by Django 5.2 on 2025-05-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_inventoryitem_alter_purchasebilldetails_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=255)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
