# Generated by Django 5.2 on 2025-05-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_trendingproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trendingproduct',
            old_name='product',
            new_name='product_name',
        ),
        migrations.AlterField(
            model_name='trendingproduct',
            name='scraped_at',
            field=models.DateTimeField(),
        ),
    ]
