# Generated by Django 5.2 on 2025-05-01 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_rename_product_trendingproduct_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingproduct',
            name='match_confidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trendingproduct',
            name='matched_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='trendingproduct',
            name='scraped_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='trendingproduct',
            table='trends_trendingproduct',
        ),
    ]
