# Generated by Django 5.2 on 2025-05-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_trendingproduct_match_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendingproduct',
            name='product_name',
            field=models.CharField(db_column='product_name', max_length=255),
        ),
    ]
