# Generated by Django 5.2 on 2025-05-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_trendingproduct_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trendingproduct',
            old_name='product_name',
            new_name='product',
        ),
    ]
